#!/bin/sh
#PBS -N KnowledgeDistillation
#PBS -q serial
#PBS -P CSCI1166
#PBS -l select=1:ncpus=10:mem=64gb
#PBS -l walltime=3:00:00
#PBS -o /mnt/lustre/users/btomkinson/kd_code/stdoutput.out
#PBS -e /mnt/lustre/users/btomkinson/kd_code/stderror.err
#PBS -m abe -M u18042717@tuks.co.za

cd /mnt/lustre/users/btomkinson/kd_code

module load chpc/python/3.7.2_gcc-8.2.0

python /mnt/lustre/users/btomkinson/kd_code/main.py

