#!/bin/sh
#PBS -N KnowledgeDistillation
#PBS -q gpu_1
#PBS -P CSCI1166
#PBS -l select=1:ncpus=10:mem=64gb
#PBS -l walltime=3:00:00
#PBS -o /mnt/lustre/users/btomkinson/kd_code/stdoutput.out
#PBS -e /mnt/lustre/users/btomkinson/kd_code/stderror.err
#PBS -m abe -M u18042717@tuks.co.za

cd /mnt/lustre/users/btomkinson/kd_code

module load chpc/python/anaconda/3-2021.11
source /mnt/lustre/users/btomkinson/my_envs/firstENV/bin/activate

python /mnt/lustre/users/btomkinson/kd_code/main.py
